### ISSUE TITLE
Update guide to mount secrets using volumes 

### ISSUE THREAD

**Issue by griffinhadfield** [OpenLiberty/guide-kubernetes-microprofile-config#126]
Update the guide to mount the secrets using volumes rather than environment variables.

Addresses https://github.com/OpenLiberty/guides-common/issues/511

This needs to wait until https://github.com/OpenLiberty/open-liberty/issues/9786 is delivered as the functionality to accomplish this is not currently released.

**Comment by gkwan-ibm** [comment]
see [Using Kubernetes secrets as Liberty config variables](https://openliberty.io/blog/2021/10/29/kube-secrets-210011.html#kubernetes_secrets) and the interactive tutorial at https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/

**Comment by gkwan-ibm** [comment]
close because the change does not relate to MicroProfile Config. It should be a Liberty feature.
