### ISSUE TITLE
Anti-pattern: No Rolling Updates

### ISSUE THREAD

**Issue by akondasif** [OpenLiberty/guide-kubernetes-microprofile-config#142]
Dear Colleague,

We are looking to find ways to help developers find security anti-patterns, i.e., violation of security best practices in Kubernetes manifests.

We have noticed an instance of not using rolling updates. Rolling updates helps to automatically apply continuous updates. Without continuous updates, a Kubernetes cluster will be susceptible to a denial of service attack, according to researchers: https://arxiv.org/pdf/2006.15275.pdf .

Location of anti-pattern:

https://github.com/OpenLiberty/guide-kubernetes-microprofile-config/blob/bb07f27e04ed3e948891a47bca50c52271a9c1cc/finish/kubernetes.yaml#L15

**Comment by gkwan-ibm** [comment]
Looks like the deployment yaml files need to be updated with `RollingUpdate` strategy and `readinessProbe`.

This guide does not focus on this topic, but we will consider to add those into the yaml file.

**Comment by gkwan-ibm** [comment]
close
- rolling update was added
