### ISSUE TITLE
Missing details in the section "Modifying inventory microservice"

### ISSUE THREAD

**Issue by hcltech84** [OpenLiberty/guide-kubernetes-microprofile-config#182]
This guide modifies 3 things in the file `SytemClient.java`: `CONTEXT_ROOT`, `SYSTEM_APP_USERNAME`, and `SYSTEM_APP_PASSWORD`. 

But only mentions 2 of them in the following paragraph:

"The changes introduced here use MicroProfile Config and CDI to inject the value of the environment variables `SYSTEM_APP_USERNAME` and `SYSTEM_APP_PASSWORD` into the SystemClient class."

For those who don't know Java, and want to follow the guide by typing instead of copy/paste, they will spend a lot of time to troubleshot the error. Me as an example.

Because of that, It would be nice if you could add `CONTEXT_ROOT` to the paragraph above as well.

**Comment by gkwan-ibm** [comment]
close
- the issue was fixed
