### ISSUE TITLE
Multipane Issue

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-kubernetes-microprofile-config#35]
- [ ] Indentations for multiplatform not implemented 

- [ ] Changing replace the name resource and ping resource files to **edit**

**Comment by ismartspace** [comment]
- [ ] `greeting`, `kubernetes.yaml` and many under Updating Kubernetes resources are not hot spotted 
- [ ] guide attribution missing at the end of README.adoc
- [ ] page-tags have tags that are not in the list
- [ ] both pom.xml in start and finish directory are not updated.

**Comment by wojtczat** [comment]
### Checklist for Post-Review
**Through the browser:**
- [x] Read through guide, making sure that the flow of the guide is good
- [x] Click all links to make sure they lead to the correct place
- [ ] Make sure hotspots, code_commands and files are correct
- [x] Run Acrolinx
- [ ] get acrolinx above 70

## modifying the name service
- [ ] "Add the greeting member to the NameResource class." highlights more lines than it should
- [ ] all mentions of "greeting member" highlights more lines than it should
## modifying ping service
- [ ] "The changes introduced here use MicroProfile Config and CDI to inject the value of the environment variables USERNAME and PASSWORD into the PingResource class." PingResource class needs hotspot
## creating a configmap and secret
- [ ] "This command deploys a ConfigMap named greeting-config to your cluster. It has a key called message with a value of " should have two hotspots in the kubernetes.yaml
## Updating Kubernetes resources
- [ ] " name-container is where the GREETING environment variable will be set." should have 2 hotspots
- [ ] "The env sections under the ping-container" env and ping-container require hotspots
- [ ] "In the kubernetes.yaml file where the containers are defined, you can see the " kubernetes.yaml needs hotspot
- [ ] "the values username and password from the Secret name-credentials." name-credentials needs hotspot
## Testing the microservices
- [ ] add mvn liberty:stop-server to the start of this section

**Comment by justineechen** [comment]
- [ ] "the values username and password from the Secret name-credentials." name-credentials needs hotspot - should highlight two lines but we can't do that yet because they are not adjacent

- "add mvn liberty:stop-server to the start of this section" - The server doesn't get started in this guide

**Comment by justineechen** [comment]
2nd round:
- [ ] guide author
- [ ] update to master
- [ ] mvn instructions
- [ ] if there is a clean comment, let consider or discuss it
- [ ] make sure liberty:stop-server before the testing (assumed testing is at the end)
- [ ] update the version of cxf-rt-rs-client and cxf-rt-rs-extension-providers to 3.2.6

**Comment by justineechen** [comment]
This guide has successfully been converted to multipane and has no blockers.
