### ISSUE TITLE
The test script isn't working on MacOS

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-kubernetes-microprofile-config#36]
Uninstalled oclint to prevent interference with other packages.
If you need oclint, you must explicitly install it.
Services are not supported on osx
git.checkout
2.10s$ git clone --depth=50 --branch=master https://github.com/OpenLiberty/guide-kubernetes-microprofile-config.git OpenLiberty/guide-kubernetes-microprofile-config
Cloning into 'OpenLiberty/guide-kubernetes-microprofile-config'...
$ cd OpenLiberty/guide-kubernetes-microprofile-config
$ git checkout -qf d767b0e1f31e55aeb599a6eb6e2df181d53cbd9b
Setting environment variables from repository settings
$ export JFROG_TOKEN=[secure]
Setting environment variables from .travis.yml
$ export CHANGE_MINIKUBE_NONE_USER=true
$ java -Xmx32m -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
$ javac -J-Xmx32m -version
javac 10.0.1
before_script.1
0.01s$ unset _JAVA_OPTIONS
before_script.2
0.04s$ cd finish
0.04s$ sudo mount --make-rshared /
mount: illegal option -- -
usage: mount [-dfruvw] [-o options] [-t external_type] special node
       mount [-adfruvw] [-t external_type]
       mount [-dfruvw] special | node
The command "sudo mount --make-rshared /" failed and exited with 1 during .
Your build has been stopped.

**Comment by gkwan-ibm** [comment]
let try to run travisTst.sh locally

**Comment by AustinSeto** [comment]
Found the commands `sudo mount --make-rshared /` and the minikube vm-driver `none` cannot be used on MacOS. The minikube bootstrapper `localkube` is also deprecated and should be replaced with `kubeadm`. 

Still looking into alternatives that can work on Mac.

**Comment by gkwan-ibm** [comment]
The travis.yml and travisTest.sh should be good if run on Linux. No plan to update them to run on MacOS for this moment.
