### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-kubernetes-microprofile-config#40]
- [ ] Doesn't work with Java 11 (needs to be synced with master) 
**NOTE: Review is complete, but the guide still needs to be tested once master branch is pulled into multipane**

**Prerequisites**
- [x] Links in this section do not open in a new tab

**Creating a ConfigMap and Secret**
- [x] "You can set it directly in `Dockerfile` with the ENV command. " -> You can set it directly in **the** Dockerfile with the ENV command. 

**Updating Kubernetes Resources**
- [x] " The env sections under the `name-container` is where the GREETING environment variable will be set." -> I think the entire chunk of code for the `name-container` should be hotspotted, not just the line that defines the name.  
- [x] "and `ping-container` containers are where the environment variables will be set." -> The first part of this sentence appears to be cut off. Also, `ping-container` should be hotspotted
- [x] "The `env` sections under the `ping-container` is where the `USERNAME` and `PASSWORD `environment variables were be set." -> env, ping-container, USERNAME and PASSWORD should be hotspotted
- [x] "you can see the `valueFrom` field which" -> hotspot only highlights one instance of `valueFrom`
- [x] " In this example configMapKeyRef gets the value `message` from the ConfigMap greeting-config" -> `message` should be hotspotted
- [x] "Similarly, secretKeyRef gets the values `username` and `password` from the Secret name-credentials." -> `username` and `password` should be hotspotted

**Tearing down the environment**
- [x] Commands don't have multipane command boxes (no green box)

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guides-common/pull/233

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-kubernetes-microprofile-config/commit/11f93a046ae84e4894d342402a242c319e565bdb
