### ISSUE TITLE
Review comments from Emily

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-kubernetes-microprofile-config#5]
- It may not be immediately clear why this is beneficial to you when developing your microservices, but Kubernetes provides some tools that allow you to conveniently configure your microservices with a setup such as the one described. 
 The above sentence is very confusing. I would say:
This guide will demonstrate a common use case on why and how to configure your microservices in Kubernetes. 

- These values can come from environment variables or elsewhere. =>
These values can come from any configured config sources, such as environment variables.

- Dockerfile for name/ping. The following 2 lines should be deleted
COPY target/liberty/wlp/usr/servers/defaultServer/bootstrap.properties /config
COPY target/liberty/wlp/usr/servers/defaultServer/server.env /config

- pom.xml in name/ping directory.
The dependencies are not ideal as they directly depend on open liberty features. It should depend on microprofile and javaee apis instead.

- in your PingResource.java, why didn't you directly inject RestClient instead of using the non-CDI, which lost the point to register the client? you can easily add @RegisterProvider(UnknownurlExceptionMapper.class) on your nameClient

**Comment by proubatsis** [comment]
@Emily-Jiang For the dependencies, this is a change that we are introducing to all of the guides. It is intentional.

**Comment by proubatsis** [comment]
`bootstrap.properties` is necessary, otherwise you get the following error when Liberty starts:

> [ERROR   ] CWWKG0075E: The value ${default.http.port} is not valid for attribute httpPort of configuration element httpEndpoint. The validation message was: Value "${default.http.port}" is not a number..

**Comment by proubatsis** [comment]
I'm not quite sure if CDI can be used in this scenario since the base url can change and we can't simply rely on a static configuration for it.

**Comment by proubatsis** [comment]
Addressed in #6

**Comment by Emily-Jiang** [comment]
1. pom.xml in name/ping directory.
The dependencies are not ideal as they directly depend on open liberty features. It should depend on microprofile and javaee apis instead.
=> you should shorten the maven dependency.
2. In your PingResource.java, why didn't you directly inject RestClient instead of using the non-CDI, which lost the point to register the client? you can easily add @RegisterProvider(UnknownurlExceptionMapper.class) on your nameClient
You should use @Inject @RestClient to inject the JAX-RS client

**Comment by proubatsis** [comment]
Hi @Emily-Jiang , I have some concerns about these changes and I don't know if they can necessarily be addressed. Please let me know if I am wrong.

> The dependencies are not ideal as they directly depend on open liberty features. It should depend on microprofile and javaee apis instead.

This is intentional as this is what we are rolling out to our existing guides as well, they used to use the java ee and mp apis in the past. Is there any reason that we shouldn’t be doing this that I should pass on to the team?

> In your PingResource.java, why didn’t you directly inject RestClient instead of using the non-CDI, which lost the point to register the client?

The baseUrl is dynamic as a target hostname is passed on each request. As I understand the MpRestClient you must configure the base url using MpConfig to use CDI. This is not ideal for the guide since the url can change on each request. As I understand it, using the builder is required due to this constraint.

**Comment by proubatsis** [comment]
> you should shorten the maven dependency
I updated #6 to remove an unused dependency.

**Comment by Emily-Jiang** [comment]
I am surprised that you have to depend on esa bundles in your pom.xml. Can you change to depend on EE 8 api and microprofile apis?

**Comment by proubatsis** [comment]
@Emily-Jiang this is a change we are intentionally rolling out to the guides. If there is a reason this should not be done, please let me know and I will bring it up to the team.
