### ISSUE TITLE
On converting to system/inventory app

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-kubernetes-microprofile-config#56]
- [x] Under Modifying system microservice: `appName` member hotspots don't match.. this variable should probably only hotspot the `  private String appName;` line.
- [x] `getProperties()` should highlight the entire method not including annotations above it
- [x] if you want to show that appName is added there you would probably be making `header` a hotspot instead to highlight that one line
- [x] distinguish is spelled incorrectly, it says "distinquish"
- [x] Under Deploying your changes, there is a typo for the word examining, it says "examing"

**Comment by proubatsis** [comment]
PR Merged #58
