### ISSUE TITLE
Additional config for Docker Windows

### ISSUE THREAD

**Issue by paul-roye** [OpenLiberty/guide-kubernetes-microprofile-config#59]
![image](https://user-images.githubusercontent.com/37868974/56292819-280c6d80-6128-11e9-8390-ca6c0573d391.png)
Or you cannot make a mvn package on start/finish

**Comment by andrewdes** [comment]
Hello @paul-roye,

Thank you for opening an issue. Instructions to enable that option have now been added in the `prerequisites` section of the guides that require the setting to be enabled. 
![image](https://user-images.githubusercontent.com/22628575/56366123-59387c80-61c0-11e9-8ab3-410916155afd.png)

You can see the change on the Kubernetes Config guide here: https://openliberty.io/guides/kubernetes-microprofile-config.html#prerequisites
