### ISSUE TITLE
Manual test the guides for 19.0.0.4 GM master

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-kubernetes-microprofile-config#62]
- 19.0.0.4 GM master
  - cl190420190419-0642
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-04-19_0807/
- Automated tests are good
- Manual test the guides against 19.0.0.4 GM master, Java11OpenJ9:
  - [x] Getting Start (Andrew)
  - [x] Kube Intro (Eveline)
         - master
         - qa
  - [x] Gradle (Justine)
  - [x] Maven Intro (Eveline)
  - [x] JWT (Justine)
  - [x] Docker (Gilbert)

Current tests instructions:
- follow the guide to test it end-to-end
- test on any platform
- If guides using docker image, make sure to run the latest docker image
    - update the Dockfile with `FROM guidesbot/olguides:cl190420190419-0642`

**Comment by evelinec** [comment]
Tested `maven-intro` guide on Mac with `Launching ServletSampleServer (Open Liberty 19.0.0.4/wlp-1.0.27.cl190420190419-0642) on Eclipse OpenJ9 VM, version 11.0.2+9 (en_CA)`.

**Comment by evelinec** [comment]
Tests performed for the `kube-intro` guide:
- on `master` branch
  - modified the parent `pom.xml` with the `installURL`
  - modified the Dockerfile for the ping and name services to pull `FROM guidesbot/olguides:cl190420190419-0642`
  - run `mvn package` and observed that the OL version used is: `[INFO] Getting: https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-04-19_0807/openliberty-all-19.0.0.4-cl190420190419-0642.zip
[INFO] To: /Users/evelinec/.m2/repository/wlp-cache/openliberty-all-19.0.0.4-cl190420190419-0642.zip`
  - From the `mvn package` logs, also observed the following information about the docker image: 
```
Image will be built as name:1.0-SNAPSHOT
[INFO] 
[INFO] Step 1/5 : FROM guidesbot/olguides:cl190420190419-0642
[INFO] Status: Downloaded newer image for guidesbot/olguides:cl190420190419-0642

Image will be built as ping:1.0-SNAPSHOT
[INFO] 
[INFO] Step 1/5 : FROM guidesbot/olguides:cl190420190419-0642
```

**Comment by evelinec** [comment]
Performed the same tests as above for the `kube-intro` guide on `qa` branch. No issues.

**Comment by evelinec** [comment]
Completed.
