### ISSUE TITLE
Consider using curl instead of using the browser's dev console to view response headers

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/guide-kubernetes-microprofile-config#83]
In this guide, we ask readers to view the response headers in the brower's dev console, but in the kubernetes intro guide, we ask users to view the response headers using curl. 

**Kubernetes Microprofile Config**
<kbd>
![image](https://user-images.githubusercontent.com/33457590/72159305-10e26f80-338a-11ea-8fdd-4ac317092d78.png)
</kbd>

**Kubernetes Intro**
<kbd>
![Screen Shot 2020-01-10 at 9 18 51 AM](https://user-images.githubusercontent.com/33457590/72159387-3cfdf080-338a-11ea-9012-3b59c479b8e8.png)
</kbd>

Using curl might make it easier since the user can just copy & paste the command and view the headers instead of trying to find it from the browser's dev console especially if they are unfamiliar with it. The only issue i can think of is if users don't have curl, but they can use Postman instead in that case.

**Sample curl output**
<kbd>
![image](https://user-images.githubusercontent.com/33457590/72159535-8d754e00-338a-11ea-9ec9-7dd47820e6ab.png)
</kbd>

**Comment by NimG98** [comment]
Fixed in https://github.com/OpenLiberty/guide-kubernetes-microprofile-config/pull/89

**Comment by ankitagrawa** [comment]
Nimrah to verify it on the master

**Comment by gkwan-ibm** [comment]
verified
